<!DOCTYPE html>
<html lang="">
    <head>
        <meta charset="utf-8" />
        <title></title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="assets/css/style.css" />
    </head>
    <body>
        <header class="header-footer">
            <figure class="logo">
                <img src="assets/images/vampire-bat.svg" alt="Logo de Soif 200">
                <p>SOIF 200</p>
            </figure>
            <nav>
                <ul class="nav">
                    <a href="#"><li>ACCUEIL</li></a>
                    <a href="#"><li>SERVICES</li></a>
                    <a href="#"><li>TARIFS</li></a>
                    <a href="#"><li>CONTACT</li></a>
                </ul>
            </nav>
        </header>
        <?php
            require "templates/$template.phtml";
        ?>
        <footer class="header-footer">
            <figure class="logo">
                <img src="assets/images/vampire-bat.svg" alt="Logo de Soif 200">
                <p>Copyright - Les dieux du code</p>
            </figure>
            <nav>
                <ul class="nav">
                    <a href="#"><li>ACCUEIL</li></a>
                    <a href="#"><li>SERVICES</li></a>
                    <a href="#"><li>TARIFS</li></a>
                    <a href="#"><li>CONTACT</li></a>
                </ul>
            </nav>
        </footer>
    </body>
</html>